name: Deploy Storybook
on: push    # paths: ["packages/client/src/**", "packages/client/.storybook"] # Trigger the action only when files change in the folders defined here
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - id: files
        uses: jitterbit/get-changed-files@v1
      - name: Install and Build ğŸ”§
        run: | # Install npm packages and build the Storybook files
          yarn install
          yarn workspace client build-storybook
      - name: Test
        run: |
          yarn workspace client tsc --noEmit
      - name: Deploy Storybook ğŸš€
        if: ${{ github.ref == 'refs/heads/main' && contains(steps.files.outputs.all, 'packages/client/') }}
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: packages/client/built-storybook # The folder that the build-storybook script generates files.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: / # The folder that we serve our Storybook files from